### ISSUE TITLE
As a xoder I want to define own data types so that I can operate on higher level objects

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod#1189]
### Rationale

The vast majority of programming languages have mechanisms to define custom data types besides built-in ones. It allows building new layers of powerful abstractions to empower programs and libraries. We should add such mechanism in XOD to later be able to express IoT programs, for example.

The way to add a new data type is to make a patch with a `xod/patch-nodes/output-self` terminal on it. If a xoder places such terminal on a `color` patch, that defines a new type with name `color` in the program. The underlying C++ data type for `color` must be defined by the xoder. Along with `State` and `evaluate` he defines a type with the name `Type` which will be used by XOD to carry values of `foo`:

```cpp
/* A potential implementation of the `color` constructor  */

struct State {
    // this is a regular state related to the patch (i.e. constructor in this case)
};

struct Type {
    uint8_t r;
    uint8_t g;
    uint8_t b;
};

void evaluate(Context ctx) {
    uint8_t r = getValue<input_R>(ctx) * 255.f;
    uint8_t g = getValue<input_G>(ctx) * 255.f;
    uint8_t b = getValue<input_B>(ctx) * 255.f;
    Type obj = { r, g, b };
    emitValue<output_OUT>(ctx, obj);
}
```

Using the `output-self` node on a patch automatically generates terminal nodes of the corresponding type: `input-color` and `output-color`.

The new type don’t cast implicitly to any other type.

Consumer C++ nodes who choose to use a custom type for some terminals, refer to the required type using fully-qualified identifiers:

```cpp
void evaluate(Context ctx) {
    bob__fun_lib__color::Type myColor;
    // or
    auto myColor2 = getValue<input_IN>(ctx);
    // or
    using Color = bob__fun_lib__color::Type;
    Color color3;
    Color color4;
}
```

When a node uses a custom type for its input, the field for that pin in the inspector is disabled with a “complex type” gag. If a custom type pin is not bound on the moment of transpilation, a new constructor node is created and its output is fed into the unbound pin. So, effictively for the `color` example we’ll get the black color on each unbound color pin.

### Acceptance criteria

- [ ] I can place an `output-self` on my patch `foo`
- [ ] When I do, the `input-foo` and `output-foo` are automatically generated in the project browser
- [ ] The items to rename and delete the generated terminals are disabled
- [ ] I can remove the `output-self` and the generated terminal nodes will be removed automatically
- [ ] I can place two `output-self` on the `foo` and that’s OK
- [ ] I can place an extra output number terminal and that’s still OK
- [ ] I can place `input-foo` and `output-foo` on a patch `bar`
- [ ] I can place `bar` on `qux` and see the corresponding bound-value widgets disabled with the “complex type” text
- [ ] I can place a few more `bar`s and add links between them
- [ ] I’m not allowed to link `bar` and any other type pin

As a practical proof, make an example library to work with colors which utilizes the new mechanism to express color values. There should be nodes:

- [ ] `color` — constructor, takes R/G/B ∈ [0; 1]
- [ ] `to-rgb` — destructor, decomposes a color into R/G/B ∈ [0; 1]
- [ ] `to-bytes` — destructor, provides byte values for each of the R, G, B components
- [ ] `from-hsv` — alternative constructor H ∈ [0; 1); S, V ∈ [0; 1]
- [ ] `to-hsv` — alternative destructor H ∈ [0; 1); S, V ∈ [0; 1]
- [ ] `rotate` — gets a color and a shift, changes the hue by offseting on the shift
- [ ] `to-string` — color formatter returning a string in the web form (`#FD4007`)

### TODO

- Should we save the generated terminals in xodballs?
- What if a xoder already has a node with name `input-foo` and he place the `output-self` on `foo`?
