### ISSUE TITLE
Provide `xod` application meta

### ISSUE THREAD

**Issue by alexander-matsievsky** [xodio/xod#471]
### Rationale

Electron build process spits out the following warnings.

> ⚠️  description is missed in the package.json (/home/alexander-matsievsky/WebstormProjects/xod/packages/xod-client-electron/package.json)
Rebuilding native production dependencies for linux:x64

> ⚠️  Application icon is not set, default Electron icon will be used

These, and other meta-values, are included into build artifacts, and should be provided.

[Icons](https://github.com/electron-userland/electron-builder#quick-setup-guide) are among others:

> Create a directory build in the root of the project and save a background.png (macOS DMG background), icon.icns (macOS app icon) and icon.ico (Windows app icon) into it.

> The Linux icon set will be generated automatically based on the macOS icns file (or you can put them into the build/icons directory if you want to specify them yourself. The filename must contain the size (e.g. 32x32.png) of the icon).

### Acceptance criteria

- [x] [package.json](packages/xod-client-electron/package.json) contains meaningful `author` field;
- [x] [package.json](packages/xod-client-electron/package.json) contains meaningful `description` field;
- [x] [package.json](packages/xod-client-electron/package.json) contains meaningful `homepage` field;
- [x] [build folder](packages/xod-client-electron/build) contains `background.png` file;
- [x] [build folder](packages/xod-client-electron/build) contains `icon.icns` file;
- [x] [build folder](packages/xod-client-electron/build) contains `icon.ico` file.
